### PR TITLE
Support ANN search for existing models

### PR DESCRIPTION
**Pull request by tqtg**
### Description

We have provided a functionality for doing ANN search in Cornac. This PR implements required functions for certain models that support the search. 

### Related Issues

#544 

### Checklist:

- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated `README.md` (if you are adding a new model).
- [ ] I have updated `examples/README.md` (if you are adding a new example).
- [ ] I have updated `datasets/README.md` (if you are adding a new dataset).

### CODE REVIEW

**Comment by saghiles** [comment]
Reviewing this PR, I will share feedback by tomorrow. Thanks :)

**Comment by tqtg** [comment]
@lthoang @saghiles let me know if you have any comments, especially for the models that you’ve contributed. Thanks

**Comment by tqtg** [comment]
knock knock

**Review by lthoang — APPROVED** [review]
I read through some models that I have contributed. The changes are fine to me.

**Pull request merged**
