### PR TITLE
Add Model Table Display into Readthedocs

### PR DESCRIPTION
**Pull request by darrylong**
### Description

In this PR, we add a JS based table into readthedocs, so as to allow filtering/sorting functions for our growing number of models. 

### Related Issues

This supports #542, which could be used for further integration.

### Checklist:

- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated `README.md` (if you are adding a new model).
- [ ] I have updated `examples/README.md` (if you are adding a new example).
- [ ] I have updated `datasets/README.md` (if you are adding a new dataset).

### CODE REVIEW

**Review by lthoang — APPROVED** [review]
LGTM

**Comment by tqtg** [comment]
@darrylong is it possible to include a few screenshots illustrating searching/filtering/sorting functions of the generated table?

**Comment by darrylong** [comment]
> @darrylong is it possible to include a few screenshots illustrating searching/filtering/sorting functions of the generated table?

Table on Readthedocs:
Screenshot 2024-06-18 at 11 01 46 AM

When filtering by keyword:
Screenshot 2024-06-18 at 11 03 09 AM

Content Based Models clicked:
Screenshot 2024-06-18 at 11 03 26 AM

Sorting when header is clicked:
Screenshot 2024-06-18 at 11 03 44 AM

**Comment by tqtg** [comment]
The table looks great. Thanks @darrylong 

There are some test errors related to Numpy version. We might need to fix them in another PR.

**Review by tqtg — APPROVED** [review]

**Pull request merged**
