### PR TITLE
Updates in VAECF: Replace deprecated functions, Support GPU, Fix progress bar issue

### PR DESCRIPTION
**Pull request by saghiles**
### Checklist:

- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated `README.md` (if you are adding a new model).
- [ ] I have updated `examples/README.md` (if you are adding a new example).

### CODE REVIEW

**Comment by tqtg** [comment]
Hi @saghiles,

Please don’t merge this PR until I test it and make sure that it works with GPU.

**Comment by saghiles** [comment]
Alright, thanks!

**Comment by tqtg** [comment]
Hi @saghiles,

I update the model to make it work with both CPU and GPU. Please take a look into the code.
If there are no more changes, we can merge this PR.

Thanks!

**Comment by saghiles** [comment]
Great! alright I'll take a look.

**Pull request merged**
