### PR TITLE
Add metadata file when saving model

### PR DESCRIPTION
**Pull request by tqtg**
### Description

Having a metadata file saved with model is handy when we want to retrieve details about the model. One of such is the model classname. 

### Checklist:

- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated `README.md` (if you are adding a new model).
- [ ] I have updated `examples/README.md` (if you are adding a new example).
- [ ] I have updated `datasets/README.md` (if you are adding a new dataset).

### CODE REVIEW

**Comment by darrylong** [comment]
Thanks @tqtg. Do we want to include trainset information (if it exists) in the metadata as well?

**Comment by tqtg** [comment]
@darrylong what is the information in trainset that we want to store in metadata?

**Comment by darrylong** [comment]
@tqtg are there any unknown issues if we were to save it with a trainset, but load it without the trainset file? If yes, then we could add the trainset=true metadata for better error handling.

**Comment by tqtg** [comment]
@darrylong line 266, we do add trainset_file in the metadata file if it’s also saved. Besides, we try to make sure any models can make predictions without trainset available. It’s kind of a best practice for model implementation.

**Pull request merged**
