### PR TITLE
Improve the main models table and example/tutorials in README

### LINKED ISSUE #609: [ASK] Is there a way to find all GPU supported models?
### Description
I could not find easily which models support GPU (I had to search in the documentation page with ctrl+F). To check which models support GPU programmatically, one can run (not all models follow the same param name, like `backend` for `MF` and `use_gpu` for several other models):
```
from cornac.models import *

models = [
AMR(),
BaselineOnly(),
Beacon(),
BiVAECF(),
BPR(),
WBPR(),
CausalRec(),
C2PF(),
CDL(),
CDR(),
COE(),
ComparERObj(),
ComparERSub(),
ConvMF(),
CTR(),
CVAE(),
CVAECF(),
DMRL(),
DNNTSP(),
EASE(),
EFM(),
# FM(), only supported on Linux.
GCMC(),
GlobalAvg(),
GPTop(),
GRU4Rec(),
HFT(),
HPF(),
HRDR(),
HypAR(),
IBPR(),
ItemKNN(),
UserKNN(),
LightGCN(),
LRPPM(),
MCF(),
MF(),
MMMF(),
MostPop(),
MTER(),
NARRE(),
GMF(),
MLP(),
NeuMF(),
NGCF(),
NMF(),
OnlineIBPR(),
PCRL(),
PMF(),
RecVAE(),
SBPR(),
SKMeans(),
SoRec(),
SPop(),
SVD(),
TIFUKNN(),
TriRank(),
UPCF(),
VAECF(),
VBPR(),
VMF(),
WMF(),
]

gpu_models = []
for model in models:
    if hasattr(model, 'use_gpu') or hasattr(model, 'backend'):
        gpu_models.append(model.name)
print(gpu_models)
```
which results in the list 
```
['AMR', 'BiVAECF', 'CausalRec', 'CVAECF', 'MF', 'GMF', 'MLP', 'NeuMF', 'SVD', 'VAECF', 'VBPR', 'VMF']
```

### Suggestions
- it would be nice to see in the model's table in README which models support GPU
- cornac could have a helper function to check which models support gpu

### PR DESCRIPTION
**Pull request by lgabs**
- Fixes #609 (specifying CPU/GPU supported for each of the models).
- Adding more links to existing examples and tutorials for the models. I think this table is where most users refer to when looking for model details. Therefore, having these links will raise visibility.

### CODE REVIEW

**Comment by tqtg** [comment]
Hey @lgabs, thanks a lot for making this changes. It will be very helpful for model references. I'm just trying to merge environment and requirement into one column to save some space when displaying the whole table in the main page.

**Comment by lgabs** [comment]
Thanks! Yeah, it will be better to save some space. I can do it too, if you didn't start this change yet.

**Comment by tqtg** [comment]
Let me try to propose some changes first and see if you're good with that.

**Comment by lgabs** [comment]
Nice, i'm good with that change, it's cleaner now.

**Comment by tqtg** [comment]
@lgabs sorry for introducing other changes to this PR. However, I think it's a good chance to have more example/tutorial links added to the main table for users reference.

**Comment by tqtg** [comment]
tagging other key contributors to seek better ideas @darrylong @lthoang @hieuddo @saghiles

**Comment by darrylong** [comment]
I agree to these changes, it's okay so long as it is readable to users.

Anyway, non-related but i'm exploring an idea to add this table to our readthedocs documentation site with a filter/sort function. This will be explored in another PR.

**Pull request merged**
