### PR TITLE
Add production version of API serving

### PR DESCRIPTION
**Pull request by darrylong**
### Description

API serving is ported to run on Flask. Flask dependency is required to run this version of serving.

In this PR, API serving have been changed to the following form:
Flask --> Gunicorn (WSGI HTTP Server) --> nginx (as a reverse proxy)

**Changes**

To run in development mode:
Run `MODEL_DIR='saved_models/bpr' MODEL_CLASS='cornac.models.BPR' flask run` where `MODEL_DIR` and `MODEL_CLASS` are saved model directory and the class of the models respectively.

### Checklist:

- [ ] I have added tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated `README.md` (if you are adding a new model).
- [ ] I have updated `examples/README.md` (if you are adding a new example).
- [ ] I have updated `datasets/README.md` (if you are adding a new dataset).

### CODE REVIEW

**Comment by tqtg** [comment]
@darrylong are we planning to have a tutorial on best practices for using this API service?

**Comment by darrylong** [comment]
Yes we should! I'll include a readme in the directory, also with the developer documentation?

**Comment by tqtg** [comment]
that would be great! Let me see how we can combine this with our current serving API. In the meantime, maybe you could help with a tutorial/guide on using this with wsgi server too.

**Comment by tqtg** [comment]
@darrylong I've updated to use Flask app as the default way to serve model. I think it's better than maintaining different versions. Let me know if we're good with this approach, then we can develop user guide accordingly.

**Comment by darrylong** [comment]
> @darrylong I've updated to use Flask app as the default way to serve model. I think it's better than maintaining different versions. Let me know if we're good with this approach, then we can develop user guide accordingly. 

@tqtg Hey thanks for the changes, they look great to me. I'm okay with Flask being used as the default way. 

Only thing is that do we want all users to install Flask in order to use Cornac?

**Comment by tqtg** [comment]
@darrylong that’s a good point. Maybe we don’t have to, and only need to tell users to install Flask as needed

**Comment by darrylong** [comment]
> @darrylong that’s a good point. Maybe we don’t have to, and only need to tell users to install Flask as needed

@tqtg alright! i was thinking maybe we can remove the dependency check from `setup.py`, and add a check in the serving portion instead. Will the be fine?

**Comment by tqtg** [comment]
Yes. We can do that

**Comment by tqtg** [comment]
LGTM

**Comment by darrylong** [comment]
@tqtg Added the changes as discussed. Please have a look and feel free to edit or merge. Thanks!

**Pull request merged**
